// Generated fixed template; no caller-provided code.
static const char automatic_war_script[]=R"EU4AUTO(# Generated by EU4LLM bridge; fixed allow-list only.
if = {
    limit = {
        exists = FRA
    }
    FRA = {
        if = {
            limit = {
                tag = FRA
                ai = yes
                exists = yes
                NOT = { has_country_flag = llm_req_war_auto_01 }
                ENG = {
                    exists = yes
                }
                is_subject = no
                has_country_flag = llm_diplomacy_locked
                NOT = { war_with = ENG }
                NOT = { truce_with = ENG }
                NOT = { alliance_with = ENG }
                has_casus_belli = { type = cb_core target = ENG }
                177 = { owned_by = ENG is_core = FRA }
            }
            log = "EU4LLM_DIAG|war_auto_01|locked_war_effect_entered"
            declare_war_with_cb = { who = ENG casus_belli = cb_core war_goal_province = 177 }
            if = {
                limit = { war_with = ENG has_country_flag = llm_diplomacy_locked ai = yes }
                set_country_flag = llm_req_war_auto_01
                log = "EU4LLM|ACK|war_auto_01|applied"
            }
            else = {
                log = "EU4LLM|ACK|war_auto_01|rejected"
            }
        }
        else = {
            log = "EU4LLM|ACK|war_auto_01|rejected"
        }
    }
}
else = {
    log = "EU4LLM|ACK|war_auto_01|rejected"
}

# Generated by EU4LLM bridge; fixed allow-list only.
if = {
    limit = {
        exists = FRA
    }
    FRA = {
        if = {
            limit = {
                tag = FRA
                ai = yes
                exists = yes
            }
            log = "EU4LLM|BEGIN|live|FRA"
            export_to_variable = { which = llm_treasury value = treasury }
            export_to_variable = { which = llm_manpower value = manpower }
            export_to_variable = { which = llm_stability value = stability }
            log = "EU4LLM|FIELD|live|treasury|[This.llm_treasury.GetValue]"
            log = "EU4LLM|FIELD|live|manpower_raw|[This.llm_manpower.GetValue]"
            log = "EU4LLM|FIELD|live|stability|[This.llm_stability.GetValue]"
            log = "EU4LLM|FIELD|live|year|[GetYear]"
            if = { limit = { ai = yes } log = "EU4LLM|FIELD|live|ai|1" }
            else = { log = "EU4LLM|FIELD|live|ai|0" }
            if = { limit = { is_at_war = yes } log = "EU4LLM|FIELD|live|war|1" }
            else = { log = "EU4LLM|FIELD|live|war|0" }
            if = { limit = { has_country_flag = llm_diplomacy_locked } log = "EU4LLM|FIELD|live|locked|1" }
            else = { log = "EU4LLM|FIELD|live|locked|0" }
            log = "EU4LLM|END|live"
            log = "EU4LLM|ACK|war_observe|applied"
        }
        else = {
            log = "EU4LLM|ACK|war_observe|rejected"
        }
    }
}
else = {
    log = "EU4LLM|ACK|war_observe|rejected"
}
)EU4AUTO";
